#!/bin/bash

BOOTFS_SOURCE=/dev/mmcblk0p3
BOOTFS_TARGET=/dev/mmcblk0p1
ROOTFS_SOURCE=/dev/mmcblk0p2
ROOTFS_TARGET=/dev/mmcblk0p4
ROOT_DEV=/dev/mmcblk0
BS=64M
DISKID=544c6228

if [ $EUID -ne 0 ]; then
    echo Must be run as root 1>&2
    exit 1
fi

echo Remounting disks read-only...
echo 1 > /proc/sys/kernel/sysrq
echo u > /proc/sysrq-trigger

echo Overwritting bootfs...
dd if=$BOOTFS_SOURCE of=$BOOTFS_TARGET bs=$BS status=progress

echo Overwritting rootfs...
dd if=$ROOTFS_SOURCE of=$ROOTFS_TARGET bs=$BS status=progress

echo Restoring original disk id...
fdisk "$ROOT_DEV" > /dev/null <<EOF
x
i
0x$DISKID
r
w
EOF

# echo Checking and resizing filesystem...
# e2fsck -f $ROOTFS_TARGET
# resize2fs $ROOTFS_TARGET

echo Done! Rebooting
sleep 1
echo b > /proc/sysrq-trigger
